server {
    listen 80;
    listen [::]:80;

    server_name assets.xdeploy.ir;
    root /var/www/xdeploy-assets;

    location / {
        try_files $uri =404;
    }

    location ~ \.sh$ {
        default_type text/plain;
        add_header X-Content-Type-Options nosniff always;
        try_files $uri =404;
    }
}
