<div
    wire:loading
    wire:target="$navigate"
    class="
        loading
        loading-bars
        loading-primary
        fixed
        top-4
        left-1/2
        z-50
        -translate-x-1/2
    "
></div>
